### ISSUE TITLE
vs2017 build, error

### ISSUE THREAD

**Issue by FoxesChen** [knik0/faac#29]
open the "project\msvc\faac.sln" with vs2017 ,build project err:“..\..\libfaac\aacquant.c”: No such file or directory

**Comment by fabiangreffrath** [comment]
Should be fixed now.

**Comment by FoxesChen** [comment]
still can't build libfaac project. 
errMsg ex:
1>f:\github\faac\libfaac\frame.c(35): error C2065: “PACKAGE_VERSION”: 未声明的标识符
1>f:\github\faac\libfaac\frame.c(35): error C2099: 初始值设定项不是常量
1>f:\github\faac\libfaac\quantize.c(249): error C2088: “-”: 对于 union 非法
1>f:\github\faac\libfaac\quantize.c(249): error C2168: “_mm_max_ps”: 内部函数的实参太少
1>f:\github\faac\libfaac\quantize.c(250): error C2088: “*=”: 对于 union 非法
1>f:\github\faac\libfaac\quantize.c(251): error C2088: “*=”: 对于 union 非法
1>f:\github\faac\libfaac\quantize.c(253): error C2088: “+=”: 对于 union 非法
1>f:\github\faac\libfaac\quantize.c(158): error C2099: 初始值设定项不是常量

**Comment by fabiangreffrath** [comment]
@FoxesChen Any chance to provide these error messages in English?

@vividos Could you have a look, please?

**Comment by FoxesChen** [comment]
1>f:\github\faac\libfaac\frame.c(35): error C2065: “PACKAGE_VERSION”: undeclared identifier
1>f:\github\faac\libfaac\frame.c(35): error C2099: Initial settings are not constants
1>f:\github\faac\libfaac\quantize.c(249): error C2088: “-”: for union illegal
1>f:\github\faac\libfaac\quantize.c(249): error C2168: “_mm_max_ps”: inner function param too little 
1>f:\github\faac\libfaac\quantize.c(250): error C2088: “=”: for union illegal
1>f:\github\faac\libfaac\quantize.c(251): error C2088: “=”: for union illegal
1>f:\github\faac\libfaac\quantize.c(253): error C2088: “+=”: for union illegal
1>f:\github\faac\libfaac\quantize.c(158): error C2099: Initial settings are not constants

**Comment by vividos** [comment]
I'll take a look in the evening, maybe the visual studio project files are outdated again, or the PACKAGE_VERSION can't be read from the configure.ac file.

**Comment by fabiangreffrath** [comment]
> 1>f:\github\faac\libfaac\frame.c(35): error C2065: “PACKAGE_VERSION”: undeclared identifier
> 1>f:\github\faac\libfaac\frame.c(35): error C2099: Initial settings are not constants

`PACKAGE_VERSION` is not defined for non-Autoconf builds.

> 1>f:\github\faac\libfaac\quantize.c(249): error C2088: “-”: for union illegal
> 1>f:\github\faac\libfaac\quantize.c(249): error C2168: “_mm_max_ps”: inner function param too little
> 1>f:\github\faac\libfaac\quantize.c(250): error C2088: “=”: for union illegal
> 1>f:\github\faac\libfaac\quantize.c(251): error C2088: “=”: for union illegal
> 1>f:\github\faac\libfaac\quantize.c(253): error C2088: “+=”: for union illegal

Seems to be some broken erithmetic with the `__m128 ` data type.

> 1>f:\github\faac\libfaac\quantize.c(158): error C2099: Initial settings are not constants

There seems to be a logic error in that line. I guess to only compile it with GCC >= 4.6 and not clang it should read
```
#if !defined(__clang__) && defined(__GNUC__) && (GCC_VERSION >= 40600)
```

**Comment by fabiangreffrath** [comment]
> Seems to be some broken erithmetic with the `__m128 ` data type.

Reverting parts of this commit might help:
https://github.com/knik0/faac/commit/02037bc1e50947fa252ffde7318bb48565dc62e4

**Comment by zvezdochiot** [comment]
https://github.com/knik0/faac/blob/dde8b0caba069abd0e1b3cbc0ed7f5c25eb1a8ff/libfaac/quantize.c#L242-L281

Maybe:

```c
#ifdef __SSE2__
          if (sse2)
          {
              for (cnt = 0; cnt < end; cnt += 4)
              {
                  __m128 x = {xr[cnt], xr[cnt + 1], xr[cnt + 2], xr[cnt + 3]};

                  x = _mm_max_ps(x, -x);
                  x *= (__m128){sfacfix, sfacfix, sfacfix, sfacfix};
                  x *= _mm_sqrt_ps(x);
                  x = _mm_sqrt_ps(x);
                  x += (__m128){MAGIC_NUMBER, MAGIC_NUMBER, MAGIC_NUMBER, MAGIC_NUMBER};

                  *(__m128i*)(xi + cnt) = _mm_cvttps_epi32(x);
              }
              for (cnt = 0; cnt < end; cnt++)
              {
                  if (xr[cnt] < 0)
                      xi[cnt] = -xi[cnt];
              }
              xi += cnt;
              xr += BLOCK_LEN_SHORT;
              continue;
          }
#else
          for (cnt = 0; cnt < end; cnt++)
          {
              double tmp = fabs(xr[cnt]);

              tmp *= sfacfix;
              tmp = sqrt(tmp * sqrt(tmp));

              xi[cnt] = (int)(tmp + MAGIC_NUMBER);
              if (xr[cnt] < 0)
                  xi[cnt] = -xi[cnt];
          }
          xi += cnt;
          xr += BLOCK_LEN_SHORT;
      }
#endif
```

**Comment by FoxesChen** [comment]
@vividos you means i install vs tools lost some config, so that  vs can't read the config file? because  i build project with mingw,  success.

**Comment by vividos** [comment]
About PACKAGE_VERSION: @knik0 added a tool to faad2 to read the package version from autoconf files and write it to a win32_ver.h:
https://github.com/knik0/faad2/tree/master/utils/win32
faac doesn't have that tool, so it doesn't compile frame.c. I could port over that tool if you want.

Next issue is in input.c:
https://github.com/knik0/faac/blob/master/frontend/input.c#L293
`bufi` is of type void*, and a value from isize is added to that pointer. MSVC complains because it isn't defined how far the pointer should be advanced; I guess this is a C++ issue (.c files are compiled as C++) and could be fixed by either changing `bufi` to `char*` or by forcing MSVC to compile as C.

The remaining issues are in quantize.c, where SSE2 code is used which doesn't compile with MSVC. I guess someone with expertise in SSE2 code on MSVC has to look at this.

**Comment by fabiangreffrath** [comment]
>  I could port over that tool if you want.

Yes, please!

> either changing `bufi` to `char*` or by forcing MSVC to compile as C.

Let's please change the pointer type. So, void pointers are treated like char pointers in pointer arithmetics in C but not in C++?

> The remaining issues are in quantize.c, where SSE2 code is used which doesn't compile with MSVC. I guess someone with expertise in SSE2 code on MSVC has to look at this.

I have already found a commit that I could revert in the critical parts and still hopefully achieve the same results.

**Comment by fabiangreffrath** [comment]
> So, void pointers are treated like char pointers in pointer arithmetics in C but not in C++?

Only in GCC:
```
In GNU C, addition and subtraction operations are supported on pointers to void and on pointers to functions. This is done by treating the size of a void or of a function as 1.
```
https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Pointer-Arith.html

**Comment by vividos** [comment]
I didn't exactly for the C language, but in C++ arithmetic with `void*` isn't valid.

**Comment by fabiangreffrath** [comment]
@FoxesChen @vividos Could you please check that the latest commits fixed compilation with MSVC without breaking anything?

**Comment by vividos** [comment]
Compiling worked for me now. I'm using Visual Studio 2019, but the conversation when opening a 2017 project is straight-forward (the wizard does everything).
I also encoded a test wav file with faac.exe and an AAC file was produced that seems to be playing correct.

**Comment by fabiangreffrath** [comment]
Phew, thanks!

**Comment by vividos** [comment]
You're welcome!
